server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loans/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"