server:
  port: 8083

spring:
  application:
    name: LOAN-SERVICE

  datasource:
    url: jdbc:h2:mem:loandb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"